-- Schema PostgreSQL para criar as tabelas do AgriFam no Supabase.
-- Execute no SQL Editor do Supabase. O backend atual ainda usa libSQL/Turso;
-- este arquivo cria o schema no Supabase, mas não troca o driver da aplicação.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null,
  created_at timestamptz not null default now(),
  constraint users_role_check check (role in ('buyer', 'producer'))
);

create table if not exists public.producers (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users (id),
  property text not null,
  location text not null,
  specialty text not null,
  rating double precision not null default 5,
  history text not null default '',
  image text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  producer_id bigint not null references public.producers (id),
  category_id bigint not null references public.categories (id),
  name text not null,
  price double precision not null,
  unit text not null,
  location text not null,
  rating double precision not null default 5,
  image text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references public.users (id),
  status text not null default 'confirmado',
  total double precision not null,
  created_at timestamptz not null default now(),
  constraint orders_status_check check (status = 'confirmado')
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id),
  product_id bigint not null references public.products (id),
  producer_id bigint not null references public.producers (id),
  product_name text not null,
  unit_price double precision not null,
  quantity integer not null,
  subtotal double precision not null
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references public.users (id),
  producer_id bigint not null references public.producers (id),
  created_at timestamptz not null default now(),
  constraint conversations_buyer_producer_unique unique (buyer_id, producer_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id),
  sender_id bigint not null references public.users (id),
  text text not null,
  created_at timestamptz not null default now()
);

-- Índices para os filtros e consultas frequentes da API.
create index if not exists products_producer_id_idx on public.products (producer_id);
create index if not exists products_category_id_idx on public.products (category_id);
create index if not exists orders_buyer_id_idx on public.orders (buyer_id);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists order_items_producer_id_idx on public.order_items (producer_id);
create index if not exists conversations_producer_id_idx on public.conversations (producer_id);
create index if not exists messages_conversation_id_created_at_idx
  on public.messages (conversation_id, created_at, id);

-- O acesso público fica bloqueado pelo Data API do Supabase sem policies.
-- O servidor deve acessar o banco com credenciais privadas, nunca com a anon key.
alter table public.users enable row level security;
alter table public.producers enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
